services:
  - type: web
    name: Skincare_Recommendation_App
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Skincare_App:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
